// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvdbqxdmtbsyefwtxghb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZGJxeGRtdGJzeWVmd3R4Z2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTY1MTIsImV4cCI6MjA2NjU5MjUxMn0.mTYI4I3EfTqzWkaI-uhBhzyOjHxotO1Hm6e_-BGjvMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);